export const items = [
  { name: "Fuji Apples", price: 10.0 },
  { name: "Pears", price: 12.0 },
  { name: "Toothpaste", price: 5.5 },
  { name: "Shampoo", price: 12.0 },
  { name: "Toothbrush", price: 5.0 },
  { name: "Butter", price: 5.0 },
  { name: "Bacon", price: 10.0 },
  { name: "Yogurt", price: 10.0 },
  { name: "Sparkling Water", price: 10.13 },
  { name: "Flour", price: 11.2 },
  { name: "Almond Butter", price: 7.5 },
  { name: "Organic Almond Butter", price: 13.5 },
  { name: "Candles", price: 13.25 },
  { name: "Bone Broth", price: 6.9 },
  { name: "Sourdough Bread", price: 4.25 },
  { name: "Peanut Butter", price: 13.5 },
  { name: "B-Complex", price: 40.0 },
  { name: "Magnesium Citrate", price: 20.0 },
  { name: "Salt", price: 5.5 },
  { name: "Sugar", price: 12.0 },
  { name: "Agave Syrup", price: 8.5 },
  { name: "Butternut Squash", price: 15.0 },
  { name: "Beef", price: 20.0 },
  { name: "Chicken Thigh", price: 9.0 },
  { name: "Free Range Eggs", price: 10.13 },
  { name: "Almond Flour", price: 11.5 },
  { name: "Orange Juice", price: 7.5 },
  { name: "Pepper", price: 4.5 },
  { name: "Coriander", price: 3.25 },
  { name: "Turmeric", price: 4.9 },
  { name: "Baking Soda", price: 4.25 },
  { name: "Tuna", price: 10.5 },
];
