export const items = [
  { name: "Fuji Apples", price: 10.0 },
  { name: "Pears", price: 12.0 },
  { name: "Toothpaste", price: 5.5 },
  { name: "Shampoo", price: 12.0 },
  { name: "Toothbrush", price: 5.0 },
  { name: "Butter", price: 5.0 },
  { name: "Bacon", price: 10.0 },
  { name: "Yogurt", price: 10.0 },
  { name: "Sparkling Water", price: 10.13 },
  { name: "Flour", price: 11.2 },
  { name: "Almond Butter", price: 7.5 },
  { name: "Organic Almond Butter", price: 13.5 },
  { name: "Candles", price: 13.25 },
  { name: "Bone Broth", price: 6.9 },
  { name: "Sourdough Bread", price: 4.25 },
  { name: "Peanut Butter", price: 13.5 },
];
